//export const INCREASE_COUNTER = "INCREASE_COUNTER"
export const actionTypes={
    LOGIN:"LOGIN",
    ADD_USER:"ADD_USER",
    UPDATE_USER:"UPDATE_USER",
    FORM_SUBMITION_STATUS:"FORM_SUBMITION_STATUS",
    HOSTNAME:"https://localhost:44335/"
}

